name: Testing the GoLang Weather Service

on: 
    push:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v2
            - name: Set up Go 1.16
              uses: actions/setup-go@v2
              with:
                  go-version: 1.21
            - name: Install dependencies
              run: go mod tidy
            
            - name: Run tests
              env:
                WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
              run: go test -v ./...