name: Markdown lint

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  markdown-testing:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure Node Js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
        
      - name: Markdown Lint
        run: markdownlint '**/*.md'